### PR TITLE
1256

### PR DESCRIPTION
**Pull request by danse**

### CODE REVIEW

**Comment by danse** [comment]
New files are too big to show up in Github, but you can see them checking out the branch. @rmehner this will have to go also in Sense, i am not sure who from your team wants to follow this process

**Comment by rmehner** [comment]
I'm gonna follow it, since you mentioned me anyway. Is there more to do than a simple update of the locations version?

**Comment by danse** [comment]
After this will get merged, i will update the angular module. Then we will have to test if old locations are still shown as expected, if the `OLD` string is visible enough, etcetera. So no big things, just keeping the process together

**Comment by rmehner** [comment]
Okay, just tell me once this is ready and I'll have a look into integrating this into Sense.

**Comment by obdulia-losantos** [comment]
:+1:

**Pull request merged**
