### PR TITLE
add coordinates to sl locations

### PR DESCRIPTION
**Pull request by emig**
- add coordinates to json/sierra_leone.json
- add file with the list of locations with missing coordinates
- add folder *mapping-coordinates-sierra-leona-locations* were this was
worked out. [Readme.md](./mapping-coordinates-sierra-leona-locations/Readme.md)
- format `readable.js` with `standard`
- add coordinates info to `readable.js` output
- generate new locations

Fixes first task of #952

### CODE REVIEW

**Comment by emig** [comment]
@skoni will add by default the parent's centroid of not present.

**Comment by emig** [comment]
@skoni will add here the deprecated locations and incorporate the coordinates to them.

**Comment by skoni** [comment]
nice, ping me when you want me to have a look

**Comment by emig** [comment]
@skoni ready for check

**Comment by skoni** [comment]
:bowtie:

**Pull request merged**
