### PR TITLE
[skip ci] remove AD(5) Locality

### PR DESCRIPTION
**Pull request by emig**
Task only talks about adding sections at this point
https://github.com/eHealthAfrica/sl-ebola-call-admin/issues/959

Rollback for Localities, will be added later

### CODE REVIEW

**Comment by danse** [comment]
3.1.1 was already released, even though i did the mistake of not updating the change log, sorry about it. Could you rename this to 3.1.2? also, could you write in the changelog that this is not breaking because we never deployed it to a production system? otherwise you can just merge and i will fix this stuff

**Comment by emig** [comment]
@danse latest release is 3.1.0

**Comment by danse** [comment]
@emig you are right, sorry, 3.1.1 was in `angular-locations`, so this is fine!

**Comment by danse** [comment]
That is a great book, by the way!

**Comment by emig** [comment]
the first book on the stock market, in spanish :) and the title is so clear about it.

**Pull request merged**
