### PR TITLE
clean code moved to angular-locations

### PR DESCRIPTION
**Pull request by emig**
removed:
- build functionality has been moved to https://github.com/eHealthAfrica/angular-locations/
- tests
- ci
- bower file

### CODE REVIEW

**Comment by emig** [comment]
@danse I am not sure if removing `bower.js` can affect angular-locations

**Comment by emig** [comment]
@skoni assigning coz I can't wait :hourglass:

**Comment by danse** [comment]
Yeah i think that at least `bower.json` should stay here, because [we are installing this with Bower in `angular-locations`](https://github.com/eHealthAfrica/angular-locations/blob/master/bower.json#L25) so it is important to have a version check there

**Comment by emig** [comment]
@danse I tested the `angular-locations`, just having the `package.json` and seemed to work. Can it be?

**Comment by skoni** [comment]
The version check happens on the basis of the git-tag when requesting the git-url. Having a bower.json in place when requesting this via bower seems more explicit and `right` to me. But when looking at angular-locations and how it is used there: the data is packaged inside the dist files, i think, we should pull in `locations` via npm in `angular-locations`. Then bower will not install `locations` as sub-dependency of `angular-locations` when that gets installed in the app repo. What do think about? Then we would just have the `locations/package.json` we already have and require `locations` in the `angular-locations/package.json`.

**Comment by danse** [comment]
`angular-locations` expects to find the files installed [as a Bower dependency](https://github.com/eHealthAfrica/angular-locations/blob/0e1db6f42be9c125fbfcd00c116f5880719304b3/Gruntfile.js#L74-L85). This works with the Git endpoint, but having a `bower.json` file together with the files helps a lot in troubleshooting dependency management. Consider for example when we want to be sure that we are not installing from a Bower cache, or similar cases.

@skoni if i get it right you suggest to use `package.json` instead of Bower. If the advantage is resolving the sub-dependency, we do not need this because we embed the files within Angular modules directly into `angular-locations` and we then distribute the modules. If the advantage is getting rid of Bower, we can do it. Anyway, Npm might require some configuration in the `package.json` in order to add the data files under `node_modules/locations` when installed, because it is intended for the installation of Javascript modules, not arbitrary files. I am not sure about this. If you are sure, we can migrate to Npm, but for the sake of our problem now, i would say that reintroducing `bower.json` is the simplest solution. I created [this pull request](https://github.com/eHealthAfrica/locations/pull/32) for it.

**Comment by skoni** [comment]
@danse Yes, that was the point. Get rid of bower and just use npm. Npm will install everything that is not ignored via .npmignore or .gitignore, so everything should be fine.

**Comment by emig** [comment]
@skoni @danse I don't have an opinion on that, shall I merge https://github.com/eHealthAfrica/locations/pull/32#event-393772953 for now and we can discuss this in an issue?

**Comment by skoni** [comment]
I would say yes, merge it.

**Comment by emig** [comment]
ok, will rewrite the tag (so is still 3.0.0)

**Pull request merged**
