### PR TITLE
CCSL-2205: missing Bombali Sebora sections

### PR DESCRIPTION
**Pull request by twitchett**

### CODE REVIEW

**Comment by emig** [comment]
json is too big, can't see anything on the diff. Which section names did you added?

**Comment by emig** [comment]
I see, makeni, konta, matotoka, khafala, ka gbara ?

**Comment by twitchett** [comment]
4 sections, but formatting is screwy. will need to fix (tomorrow)

**Comment by emig** [comment]
the parentId should be "21-01" for them

**Pull request closed without merging**
