### PR TITLE
adds geocordinates to SL sections + add ochaId to SL locations

### PR DESCRIPTION
**Pull request by emig**
depends on https://github.com/eHealthAfrica/locations/pull/45 for easy check of the differences on the `json` file and probably requires rebase/merge after that is merged

add coordinates(sections) & ocha id SL

change: the `Location` class to
- load Location hierarchy from current `json` file
- order by id

add:
- add ocha id werever we can
- coordinates to sections

fix:
- fix misspelling error in moyamba district
- correct errors in kailahun
- match admindivision3 id and on the match match admindivision4 name to
add the coordinates

close https://github.com/eHealthAfrica/sl-ebola-call-admin/issues/1029
    add coordinates(sections) & ocha id SL

    change: the `Location` class to
    - load Location hierarchy from current `json` file
    - order by id

    add:
    - add ocha id werever we can
    - coordinates to sections

    fix:
    - fix misspelling error in moyamba district
    - correct errors in kailahun
    - match admindivision3 id and on the match match admindivision4 name to
      add the coordinates

    close https://github.com/eHealthAfrica/sl-ebola-call-admin/issues/1029
    close https://github.com/eHealthAfrica/sl-ebola-call-admin/issues/1072

requires release 3.2.0

### CODE REVIEW

**Comment by emig** [comment]
@skoni  OCHA is an acronym, shall I change the property name from `ochaId` -> `OCHAId` ?

**Comment by skoni** [comment]
i think `ochaId` is fine.

**Comment by emig** [comment]
@skoni we probaby don't want ochaId present on the angular module, to prevent it growing in size. Can you add a task that needs to be added there (filtering out that info)?

**Comment by skoni** [comment]
:tada: :star:

**Pull request merged**
